spring.application.name=Projet_Pi_V2

# MongoDB - URI format (plus fiable)
spring.data.mongodb.uri=mongodb://localhost:27017/ShowMatchGoOn

# Port
server.port=8091

# JWT
security.jwt.secret-key=change-this-secret-key-to-a-strong-random-value-256bits
security.jwt.expiration-ms=86400000

# ? Ajout Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mejrielee932@gmail.com
spring.mail.password=ybcnzujqttavydiv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com