spring.application.name=Projet_Pi_V2
# MongoDB connection
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=ShowMtachGoOn

# Si tu veux mettre un utilisateur/mot de passe plus tard
# spring.mongodb.username=ton_user
# spring.mongodb.password=ton_mdp

# Port de ton application
server.port=8091

# JWT configuration
security.jwt.secret-key=change-this-secret-key-to-a-strong-random-value-256bits
security.jwt.expiration-ms=86400000
